#!/usr/bin/env python                                                                                                                                                                                    
intLumi = 2460
cutName = 'trigger'
input_sources = [
    { 'condor_dir' : 'NoBPTX2016Data_TriggerTurnOn',
      'dataset' :   'NoBPTX_2016BCD_PromptReco_OnlyControlTriggers_Ntuple',
      'den_channel' : 'PreSelectionUpperLowerTurnOnDen',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum35',
      'num_channel' : 'PreSelectionUpperLowerTurnOnNum40',
      'legend_entry' : 'NoBPTX 2016B-D Prompt reco data',
      'color' : 'black',
      #'fill' : '',
      'marker' : 'circle',
      },
    #{ 'condor_dir' : 'NoBPTX2016Data_TriggerTurnOn',
      #'dataset' :   'NoBPTX_2016B_PromptReco_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'PreSelectionUpperLowerTurnOnDen',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum35',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum40',
      #'legend_entry' : 'NoBPTX 2016B Prompt reco data',
      #'color' : 'red',
      #'fill' : '',
      #'marker' : 'square',
      #},
    #{ 'condor_dir' : 'NoBPTX2016Data_TriggerTurnOn',
      #'dataset' :   'NoBPTX_2016C_PromptReco_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'PreSelectionUpperLowerTurnOnDen',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum35',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum40',
      #'legend_entry' : 'NoBPTX 2016C Prompt reco data',
      #'color' : 'blue',
      #'fill' : '',
      #'marker' : 'triangle',
      #},
    #{ 'condor_dir' : 'NoBPTX2016Data_TriggerTurnOn',
      #'dataset' :   'NoBPTX_2016D_PromptReco_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'PreSelectionUpperLowerTurnOnDen',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum35',
      #'num_channel' : 'PreSelectionUpperLowerTurnOnNum40',
      #'legend_entry' : 'NoBPTX 2016D Prompt reco data',
      #'color' : 'green',
      #'fill' : 'hollow',
      #'marker' : 'circle',
      #},
]
