input_sources = [
  { 'condor_dir' : '2ndJetAnalysis',
    'dataset' : 'g2qqchi_1200_200',
    'channel' : 'SecondJetSelection',
    'legend_entry' : '#tilde{g}#rightarrow u#bar{u}#tilde{#chi}^{0} m_{#tilde{g}}=1200GeV, m_{#tilde{#chi}^{0}}=200GeV',
    'color' : 'blue',
    'fill'  : 'solid',
    'marker' : 'triangle',
    },
  { 'condor_dir' : '2ndJetAnalysis',
    'dataset' : 'g2qqchi_1200_600',
    'channel' : 'SecondJetSelection',
    'legend_entry' : '#tilde{g}#rightarrow u#bar{u}#tilde{#chi}^{0} m_{#tilde{g}}=1200GeV, m_{#tilde{#chi}^{0}}=600GeV',
    'color' : 'red',
    'fill'  : 'solid',
    'marker' : 'circle',
    },
  { 'condor_dir' : '2ndJetAnalysis',
    'dataset' : 'g2qqchi_1200_1000',
    'channel' : 'SecondJetSelection',
    'legend_entry' : '#tilde{g}#rightarrow u#bar{u}#tilde{#chi}^{0} m_{#tilde{g}}=1200GeV, m_{#tilde{#chi}^{0}}=1000GeV',
    'color' : 'green',
    'fill'  : 'solid',
    'marker' : 'square',
    },
]
