#!/usr/bin/env python

intLumi = 2460
cutName = 'trigger'
input_sources = [
    { 'condor_dir' : 'NoBPTX2016CDData_Jets_TriggerTurnOn',
      'dataset' :   'NoBPTX_2016BCDEFG_PromptReco_Jets_OnlyControlTriggers_Ntuple',
      'den_channel' : 'DenominatorTriggerTurnOnSelection2016',
      'num_channel' : 'NumeratorTriggerTurnOnSelection2016',
      'legend_entry' : 'Run 2016C-D',
      'color' : 'black',
      #'fill' : '',
      'marker' : 'circle',
      },

    #{ 'condor_dir' : 'NoBPTX2016CDData_Jets_TriggerTurnOn',
      #'dataset' :   'NoBPTX_2016BCDEFG_PromptReco_Jets_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'NoCuts',
      #'num_channel' : 'TriggerSelection2016',
      #'legend_entry' : 'NoBPTX 2016C-D Prompt reco data, no cuts',
      #'color' : 'red',
      #'fill' : '',
      #'marker' : 'square',
      #},
    #{ 'condor_dir' : 'NoBPTX2016Data_Jets_TriggerTurnOn_Preselection',
      #'dataset' :   'NoBPTX_2016B_PromptReco_Jets_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'DenominatorTriggerTurnOnSelection2016',
      #'num_channel' : 'NumeratorTriggerTurnOnSelection2016',
      #'legend_entry' : 'NoBPTX 2016B Prompt reco data',
      #'color' : 'red',
      #'fill' : '',
      #'marker' : 'square',
      #},
    #{ 'condor_dir' : 'NoBPTX2016Data_Jets_TriggerTurnOn_Preselection',
      #'dataset' :   'NoBPTX_2016C_PromptReco_Jets_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'DenominatorTriggerTurnOnSelection2016',
      #'num_channel' : 'NumeratorTriggerTurnOnSelection2016',
      #'legend_entry' : 'NoBPTX 2016C Prompt reco data',
      #'color' : 'blue',
      #'fill' : '',
      #'marker' : 'triangle',
      #},
    #{ 'condor_dir' : 'NoBPTX2016Data_Jets_TriggerTurnOn_Preselection',
      #'dataset' :   'NoBPTX_2016D_PromptReco_Jets_OnlyControlTriggers_Ntuple',
      #'den_channel' : 'DenominatorTriggerTurnOnSelection2016',
      #'num_channel' : 'NumeratorTriggerTurnOnSelection2016',
      #'legend_entry' : 'NoBPTX 2016D Prompt reco data',
      #'color' : 'green',
      #'fill' : 'hollow',
      #'marker' : 'circle',
      #},
]
